controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController

arm_controller:
  ros__parameters:
    joints: [joint1, joint2, joint3, joint4, joint5, joint6]
    command_interfaces: [effort]
    state_interfaces: [position, velocity]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    gains:
      joint1: {p: 120.0, i: 0.0, d: 12.0, i_clamp: 0.0, ff_velocity_scale: 0.0}
      joint2: {p: 140.0, i: 0.0, d: 14.0, i_clamp: 0.0, ff_velocity_scale: 0.0}
      joint3: {p: 110.0, i: 0.0, d: 11.0, i_clamp: 0.0, ff_velocity_scale: 0.0}
      joint4: {p: 55.0, i: 0.0, d: 5.0, i_clamp: 0.0, ff_velocity_scale: 0.0}
      joint5: {p: 35.0, i: 0.0, d: 3.5, i_clamp: 0.0, ff_velocity_scale: 0.0}
      joint6: {p: 20.0, i: 0.0, d: 2.0, i_clamp: 0.0, ff_velocity_scale: 0.0}

gripper_controller:
  ros__parameters:
    joint: gripper_joint1
    goal_tolerance: 0.002
    max_effort: 20.0
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
